name: MLOps Pipeline

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python src/pipeline/training_pipeline.py

    - name: Build Docker image
      run: |
        docker build -t healthcare-mlops .